department_app/views/routes.py
from flask import Blueprint, render_template

routes = Blueprint('routes', __name__, static_folder='static')


@routes.route('/')
def main():
    """
    Route for welcome page, it's like menu for further interactions
    """
    return render_template("main.html")


@routes.route('/employees')
def employees():
    """
    Route for employee table, shows all employees in table
    """
    # gather data from db about all employees
    return render_template("employees.html")


@routes.route('/departments')
def departments():
    """
    Route for departments table, shows all departments in table
    """
    # gather data from db about all departments
    return render_template("departments.html")


@routes.route('/employee/<employee_id>')
def employee(employee_id):
    """
    Route for employee table, shows all employees in table
    """
    # gather data from db about all employees
    return render_template("employee.html",
                           employee_id=employee_id)


@routes.route('/department/<department_id>')
def department(department_id):
    """
    Route for employee table, shows all employees in table
    """
    # gather data from db about all employees
    return render_template("department.html",
                           department_id=department_id)

department_app/templates/department.html
{% extends "table_pages.html" %}
{% block title %}DepartmentCRUD{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-center" id="all_content">
        <!-- Place for table with employees -->
        <div class="p-2">
            <h5 class="card-title" id="form_title">Create a copy of the department</h5>
            <form id="insert_form">
            <div class="form-group row">
                <label for="department_name" class="col-4 col-form-label">Department name</label>
                <div class="col-8">
                    <input id="department_name" name="department_name" placeholder="department name" type="text" required="required" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 col-8">
                    <input id="employee_id" name="department_id" hidden type="text" class="form-control" value="{{ department_id }}">
                    <button id="insert_btn" class="btn btn-outline-success" type="submit">Submit</button>
                </div>
            </div>
            </form>
            <button id="delete_button" class="btn btn-outline-danger">Delete department</button>
            <button id="update_button" class="btn btn-outline-warning">Change department info</button>

        </div>
    </div>
{% endblock %}

{% block datatable_script %}
    <script type="text/javascript">
        let department_id = "{{ department_id }}"
        let department_address = "{{ url_for('routes.departments') }}"
    </script>
    <script src="{{ url_for('routes.static', filename='department.js') }}"></script>
{% endblock %}

department_app/templates/departments.html
{% extends "table_pages.html" %}
{% block title %}DepartmentsCRUD{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-center">
        <!-- Place for table with employees -->
        <div class="p-2">
            <h5 class="card-title" id="form_title">Insert new department</h5>
            <form id="insert_form">
            <div class="form-group row">
                <label for="department_name" class="col-4 col-form-label">Department name</label>
                <div class="col-8">
                    <input id="department_name" name="department_name" placeholder="department name" type="text" required="required" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 col-8">
                    <input id="employee_id" name="department_id" hidden type="text" class="form-control">
                    <button id="insert_btn" class="btn btn-outline-success" type="submit">Submit</button>
                </div>
            </div>
            </form>
        </div>
    </div>
    <button id="delete_button" class="btn btn-outline-danger">Delete selected rows</button>
    <button id="update_button" class="btn btn-outline-warning">Update selected row</button>
    <table id="data_table" class="display table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Department name</th>
            <th>Average salary</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
        <tr>
            <th>Department name</th>
            <th>Average salary</th>
        </tr>
        </tfoot>
    </table>
{% endblock %}

{% block datatable_script %}
    <script src="{{ url_for('routes.static', filename='departments_table.js') }}"></script>
{% endblock %}

department_app/templates/employee.html
{% extends "table_pages.html" %}
{% block title %}EmployeeCRUD{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-center" id="all_content">
        <!-- Place for table with employees -->
        <div class="p-2">
            <h5 class="card-title" id="form_title">Create a copy of the employee</h5>
            <form id="insert_form">
            <div class="form-group row">
                <label for="employee_name" class="col-4 col-form-label">Name</label>
                <div class="col-8">
                    <input id="employee_name" name="employee_name" placeholder="employee name" type="text" required="required" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="date_of_birth" class="col-4 col-form-label">Date of birth</label>
                <div class="col-8">
                    <input id="date_of_birth" name="date_of_birth" placeholder="format: 1999" type="date" required="required" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="salary" class="col-4 col-form-label">Salary</label>
                <div class="col-8">
                    <input id="salary" name="salary" type="number" required="required" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="department_name" class="col-4 col-form-label">Department name</label>
                <div class="col-8">
                    <input id="department_name" name="department_name" required="required" type="text" class="form-control">
                    <input id="employee_id" name="employee_id" hidden type="text" value="{{ employee_id }}" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <button id="insert_btn" class="btn btn-outline-success" type="submit">Submit</button>

                </div>
            </div>
        </form>
            <button id="delete_button" class="btn btn-outline-danger">Delete employee</button>
            <button id="update_button" class="btn btn-outline-warning">Change employee info</button></div>
    </div>

{% endblock %}

{% block datatable_script %}
    <script type="text/javascript">
        let employee_id = "{{ employee_id }}"
        let employees_address = "{{ url_for('routes.employees') }}"
    </script>
    <script type="text/javascript" src="{{ url_for('routes.static', filename='employee.js') }}"></script>
{% endblock %}

department_app/templates/employees.html
{% extends "table_pages.html" %}
{% block title %}EmployeeCRUD{% endblock %}

{% block content %}
<div class="d-flex flex-row justify-content-center">
    <!-- Place for table with employees -->
    <div class="p-2">Card 1</div>
    <div class="p-2">Card 2</div>
</div>
<table id="data_table" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th>Name</th>
        <th>Date of birth</th>
        <th>Salary</th>
        <th>Department name</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th>Name</th>
        <th>Date of birth</th>
        <th>Salary</th>
        <th>Department name</th>
    </tr>
    </tfoot>
</table>
{% endblock %}

{% block datatable_script %}
<script>
    $(document).ready(function() {
        $('#data_table').DataTable({
            "ajax": '/employee_crud'
        });
    } );
</script>
{% endblock %}

department_app/templates/main.html
{% extends "table_pages.html" %}
{% block title %}Main page{% endblock %}

{% block content %}
<div class="d-flex flex-row justify-content-center">
    <!-- Place for table with employees -->
    <div class="p-2">Card 1</div>
    <div class="p-2">Card 2</div>
</div>
{% endblock %}

department_app/templates/table_pages.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title{% endblock %}</title>
    <!-- Bootstrap and Datatable CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.2.8/css/responsive.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" rel="stylesheet">

    <!-- Bootstrap and Datatable Javascript -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.8/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.8/js/responsive.bootstrap4.min.js"></script>
{% endblock %}
</head>
<body>
{% block body %}
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">EPAM Python winter 2021 project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" id="nav_home" aria-current="page" href="/">Home</a>
                        <a class="nav-link" id="nav_dep" href="{{ url_for("routes.departments") }}">Departments</a>
                        <a class="nav-link" id="nav_emp" href="{{ url_for("routes.employees") }}">Employees</a>
                    </div>
                </div>
            </div>
        </nav>
    {% endblock %}
    {% block content %}
    <!-- Place for global content -->
    {% endblock %}
    {% block footer %}
        <footer class="card-footer"></footer>
    {% endblock %}
{% endblock %}
<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

{% block navbar_script %}
<script>
    $('.navbar').ready(function() {
        $(".nav-link").each(function() {
            if ($(this).attr('href') === window.location.pathname) {
                $(this).addClass("active");
            }
        });
    });
</script>
{% endblock %}
{% block datatable_script %}
{% endblock %}
</body>
</html>